version: 2
jobs:
  test:
    docker:
      - image: circleci/rust:1.35-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            cargo build
            cargo install diesel_cli
            diesel migration run --database-url=test.db
      - run:
          name: run test suite
          command: |
            cargo test

workflows:
  version: 2
  format_and_test:
    jobs:
      - test
