version: 2
jobs:
  test:
    docker:
      - image: circleci/rust:1.35-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Cargo.lock" }}
      - run:
          name: install dependencies
          command: |
            cargo build
      - save_cache:
          paths:
            - ~/.cargo
          key: v1-dependencies-{{ checksum "Cargo.lock" }}
      - run:
          name: run test suite
          command: |
            cargo test

workflows:
  version: 2
  format_and_test:
    jobs:
      - test
